spring:
  profiles:
    active: dev
  datasource:
    mybatis:
      druid:
        a:
          type: com.alibaba.druid.pool.DruidDataSource
          name: dataSourceA
          username: root
          password: root
          url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&useCompression=true&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
          driver-class-name: com.mysql.jdbc.Driver
          maxActive: 20
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
        b:
          type: com.alibaba.druid.pool.DruidDataSource
          name: dataSourceB
          username: root
          password: root
          url: jdbc:mysql://localhost:3306/study2?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&useCompression=true&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
          driver-class-name: com.mysql.jdbc.Driver
          maxActive: 20
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
  application:
    name: mybatistest
  kafka:
    bootstrap-servers: 192.168.11.100:9092,192.168.11.101:9092,192.168.11.102:9092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: test1
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#配置分页
pagehelper:
  offset-as-page-num: true
  row-bounds-with-count: true

server:
  port: 8081
#  servlet:
#    context-path: /mybatistest